name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer

      - name: Install dependencies
        run: |
          # Commands to install any dependencies, if applicable
          echo "No additional dependencies to install."

      - name: Build project
        run: xcodebuild -project Airbnb.xcodeproj -scheme Airbnb -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0' build

      - name: Run tests
        run: xcodebuild test -project Airbnb.xcodeproj -scheme Airbnb -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
